name: Publish to NPM

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 0.2.0)'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Needed for NPM provenance via OIDC
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Update version if manual trigger
        if: github.event_name == 'workflow_dispatch'
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          # Also update the gateway version in package.json
          node -e "
          const fs = require('fs');
          const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
          pkg.tokligenceGateway.version = '${{ github.event.inputs.version }}';
          fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\\n');
          "

      - name: Run tests
        run: npm test
        continue-on-error: true

      - name: Publish to NPM with provenance
        run: npm publish --access public --provenance

      - name: Create GitHub Release (if manual)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release v${{ github.event.inputs.version }}
          body: |
            ## Changes in this release
            - Updated to Tokligence Gateway v${{ github.event.inputs.version }}

            ## Installation
            ```bash
            npm install -g @tokligence/gateway@${{ github.event.inputs.version }}
            ```
          draft: false
          prerelease: false